name: user_api
description: User API Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
