// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cat.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Cat _$CatFromJson(Map<String, dynamic> json) {
  return Cat(
    weight:
        Weight.fromJson(json['weight'] as Map<String, dynamic>? ?? const {}),
    id: json['id'] as String? ?? '',
    name: json['name'] as String? ?? '',
    cfa_url: json['cfa_url'] as String? ?? '',
    vetstreet_url: json['vetstreet_url'] as String? ?? '',
    vcahospitals_url: json['vcahospitals_url'] as String? ?? '',
    temperament: json['temperament'] as String? ?? '',
    origin: json['origin'] as String? ?? '',
    country_codes: json['country_codes'] as String? ?? '',
    country_code: json['country_code'] as String? ?? '',
    description: json['description'] as String? ?? '',
    life_span: json['life_span'] as String? ?? '',
    indoor: json['indoor'] as int? ?? 0,
    lap: json['lap'] as int? ?? 0,
    adaptability: json['adaptability'] as int? ?? 0,
    affection_level: json['affection_level'] as int? ?? 0,
    child_friendly: json['child_friendly'] as int? ?? 0,
    cat_friendly: json['cat_friendly'] as int? ?? 0,
    dog_friendly: json['dog_friendly'] as int? ?? 0,
    energy_level: json['energy_level'] as int? ?? 0,
    grooming: json['grooming'] as int? ?? 0,
    health_issues: json['health_issues'] as int? ?? 0,
    intelligence: json['intelligence'] as int? ?? 0,
    shedding_level: json['shedding_level'] as int? ?? 0,
    social_needs: json['social_needs'] as int? ?? 0,
    stranger_friendly: json['stranger_friendly'] as int? ?? 0,
    vocalisation: json['vocalisation'] as int? ?? 0,
    bidability: json['bidability'] as int? ?? 0,
    experimental: json['experimental'] as int? ?? 0,
    hairless: json['hairless'] as int? ?? 0,
    natural: json['natural'] as int? ?? 0,
    rare: json['rare'] as int? ?? 0,
    rex: json['rex'] as int? ?? 0,
    suppressed_tail: json['suppressed_tail'] as int? ?? 0,
    short_legs: json['short_legs'] as int? ?? 0,
    wikipedia_url: json['wikipedia_url'] as String? ?? '',
    hypoallergenic: json['hypoallergenic'] as int? ?? 0,
    reference_image_id: json['reference_image_id'] as String? ?? '',
  );
}

Map<String, dynamic> _$CatToJson(Cat instance) => <String, dynamic>{
      'weight': instance.weight.toJson(),
      'id': instance.id,
      'name': instance.name,
      'cfa_url': instance.cfa_url,
      'vetstreet_url': instance.vetstreet_url,
      'vcahospitals_url': instance.vcahospitals_url,
      'temperament': instance.temperament,
      'origin': instance.origin,
      'country_codes': instance.country_codes,
      'country_code': instance.country_code,
      'description': instance.description,
      'life_span': instance.life_span,
      'indoor': instance.indoor,
      'lap': instance.lap,
      'adaptability': instance.adaptability,
      'affection_level': instance.affection_level,
      'child_friendly': instance.child_friendly,
      'cat_friendly': instance.cat_friendly,
      'dog_friendly': instance.dog_friendly,
      'energy_level': instance.energy_level,
      'grooming': instance.grooming,
      'health_issues': instance.health_issues,
      'intelligence': instance.intelligence,
      'shedding_level': instance.shedding_level,
      'social_needs': instance.social_needs,
      'stranger_friendly': instance.stranger_friendly,
      'vocalisation': instance.vocalisation,
      'bidability': instance.bidability,
      'experimental': instance.experimental,
      'hairless': instance.hairless,
      'natural': instance.natural,
      'rare': instance.rare,
      'rex': instance.rex,
      'suppressed_tail': instance.suppressed_tail,
      'short_legs': instance.short_legs,
      'wikipedia_url': instance.wikipedia_url,
      'hypoallergenic': instance.hypoallergenic,
      'reference_image_id': instance.reference_image_id,
    };
